<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.de-gupta</groupId>
        <artifactId>security.parent</artifactId>
        <version>0.1.0</version>
    </parent>

    <artifactId>security.argus.spring</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <name>${artifactId}</name>
    <description>A spring wrapper for the library for orchestrating the authentication using tokens</description>
    <url>https://github.com/de-gupta/security.argus.spring.git</url>

    <properties>
        <spring.boot.version>3.5.13</spring.boot.version>

        <security.argus.version>0.0.1-SNAPSHOT</security.argus.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <scm>
        <connection>scm:git:ssh://git@github.com/de-gupta/security.argus.spring.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/de-gupta/security.argus.spring.git</developerConnection>
        <url>https://github.com/de-gupta/security.argus.spring.git</url>
        <tag>HEAD</tag>
    </scm>
</project>